import 'dart:io';

enum AppLocale { zh, en }

extension AppLocaleExt on AppLocale {
  String get code => this == AppLocale.zh ? 'zh' : 'en';

  String get nativeName => this == AppLocale.zh ? '中文' : 'English';
}

AppLocale localeFromCode(String? code) =>
    code == 'zh' ? AppLocale.zh : AppLocale.en;

AppLocale localeFromName(String name) {
  final lower = name.toLowerCase();
  return lower.startsWith('zh') ? AppLocale.zh : AppLocale.en;
}

AppLocale systemLocale() => localeFromName(Platform.localeName);

class Dictionary {
  const Dictionary._();

  static const Map<String, String> zh = <String, String>{
    'app.title': 'audio.cpp Desk',
    'nav.models': '模型库',
    'nav.downloads': '下载',
    'nav.voices': '音色库',
    'nav.server': '服务端',
    'nav.workbench': '工作台',
    'nav.settings': '设置',
    'nav.history': '历史',
    'history.title': '历史记录（开发中）',
    'history.hint': 'TTS/克隆/分离等任务的生成历史将保存在这里。',
    'workbench.noModels': '暂无已安装的 TTS / ASR 模型，请先到模型库安装。',
    'task.busy.title': '任务进行中',
    'task.busy.message': '当前有任务正在生成。你可以先暂停它，或等它完成后再操作。',
    'task.busy.goWorkbench': '去工作台',
    'workbench.model': '模型',
    'workbench.textHint': '输入要朗读的文本...',
    'workbench.voice': '音色',
    'workbench.defaultVoice': '默认',
    'workbench.referenceText': '参考文本',
    'workbench.referenceTextHint': '可选：参考音频对应的文本',
    'workbench.instruction': '指令 / 风格',
    'workbench.voiceId': '内置音色',
    'workbench.customVoice': '自定义…',
    'workbench.needInstruction': '该模型要求填写指令/风格',
    'workbench.language': '语言',
    'workbench.pickAudio': '选择音频',
    'workbench.submit': '加入任务',
    'workbench.advanced': '高级',
    'workbench.advancedTitle': '高级参数',
    'workbench.reset': '重置',
    'workbench.default': '默认',
    'workbench.defaultValue': '默认（{value}）',
    'workbench.invalidValue': '“{name}” 取值无效',
    'workbench.emotion': '情感',
    'workbench.emotion.none': '默认',
    'workbench.emotion.reference': '情感参考音频',
    'workbench.emotion.vector': '情感向量',
    'workbench.emotion.text': '情感文本',
    'workbench.emotion.strength': '情感强度',
    'workbench.emotion.pickAudio': '选择情感参考音频',
    'workbench.emotion.needAudio': '请先选择情感参考音频',
    'workbench.result': '结果',
    'workbench.needText': '请先输入文本',
    'workbench.needReference': '该模型需要参考音色，请先选择',
    'workbench.needReferenceText': '该模型要求填写参考文本',
    'workbench.needAudio': '请先选择音频',
    'workbench.serverNotReady':
        '服务端未就绪，请先在“服务”页配置 audio.cpp 版本并启动。',
    'workbench.memoryReleaseFailed':
        '显存无法释放，已停止生成队列。请到“服务”页重启服务端后再继续。',
    'workbench.error': '提交失败',
    'workbench.modelMissing': '模型不可用（可能已卸载）',
    'workbench.wavOnly': '未找到内置转码器，当前仅支持 WAV 音频',
    'workbench.transcodeFailed': '音频转码失败',
    'workbench.saved': '已保存到 {path}',
    'workbench.generating': '生成中 · {time}',
    'workbench.elapsed': '用时 {time}',
    'player.play': '播放',
    'player.pause': '暂停',
    'session.name': '会话名',
    'session.unnamed': '未命名会话',
    'session.new': '新建会话',
    'session.records': '会话记录',
    'session.tasks': '任务',
    'task.queued': '排队中',
    'task.pause': '暂停',
    'task.resume': '开始',
    'task.clear': '清空',
    'session.empty': '暂无生成记录',
    'session.open': '打开',
    'session.delete': '删除会话',
    'session.deleteConfirm': '删除该会话及其音频？',
    'session.record.delete': '删除记录',
    'session.export': '导出',
    'session.saved': '已保存',
    'history.empty': '暂无历史会话',
    'history.records': '{count} 条记录',
    'history.clear': '清空历史',
    'history.clearConfirm': '删除全部会话及其音频？',
    'history.opened': '已载入会话',
    'collection.none': '未归类',
    'collection.unnamed': '集合',
    'collection.label': '集合',
    'collection.new': '新建集合',
    'collection.delete': '删除集合',
    'collection.deleteConfirm': '移除该集合？其中的会话将保留为未归类。',
    'collection.move': '移动到集合',
    'collection.up': '上移',
    'collection.down': '下移',
    'record.status.generating': '生成中',
    'record.status.done': '已完成',
    'record.status.failed': '失败',
    'record.noOutput': '无输出',
    'record.type.tts': '语音合成',
    'record.type.asr': '语音识别',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.close': '关闭',
    'common.copied': '已复制',
    'common.copyFailed': '复制失败',
    'common.download': '下载',
    'common.manage': '管理',
    'common.uninstall': '卸载',
    'common.delete': '删除',
    'settings.title': '设置',
    'settings.directories': '目录',
    'settings.dataRestart': '数据目录已更改，请重启软件。',
    'settings.language': '语言',
    'settings.showExperimental': '显示实验性条目',
    'settings.showExperimental.subtitle':
        '模型库中显示 experimental / community 等未完全支持条目',
    'settings.serverLog': '服务端日志落盘',
    'settings.serverLog.subtitle':
        '保存服务端运行日志到 {dir}，便于排查问题',
    'settings.appLog': '应用日志',
    'settings.appLog.subtitle':
        '记录应用自身的运行信息（目录、模型库、任务、错误等）到 {dir}，便于排查问题',
    'settings.taskTimeout': '单次任务超时',
    'settings.taskTimeout.subtitle': '超过该时长任务仍未完成则主动判定失败',
    'settings.audioCppDesc': 'audio.cpp 版本目录（可含多个版本）',
    'settings.audioCppHint': 'audio.cpp 或绝对路径',
    'settings.modelsLabel': '模型权重目录',
    'settings.modelsHint': 'models 或绝对路径',
    'settings.dataLabel': '数据目录（备份=复制该目录）',
    'settings.dataHint': 'data 或绝对路径',
    'settings.saved':
        '目录已保存（audio.cpp / models / data），服务页将自动重新扫描。',
    'settings.pickDir': '选择目录',
    'settings.about': '关于',
    'settings.about.desc':
        'audio.cpp 的桌面客户端。audio.cpp 本体不随本软件提供，需另行获取。',
    'settings.about.source':
        '模型规格与描述派生自 audio.cpp 官方仓库与文档（Apache-2.0，© ShugoAI LLC）。',
    'settings.about.license': '开源许可',
    'settings.about.homepage': '项目',
    'settings.about.upstream': '上游项目',
    'models.currentVersion': '当前版本',
    'server.title': '服务控制',
    'server.status.label': '服务端',
    'server.status.start': '启动',
    'server.status.stop': '停止',
    'server.status.models': '已注册模型 {count}',
    'server.status.backend': '后端',
    'server.backend': '后端',
    'server.readingBackends': '正在读取后端支持列表，请稍候…',
    'server.device': '设备',
    'server.device.cpu': 'CPU',
    'server.device.gpuItem': 'GPU {index} · {name}',
    'server.threads': '线程',
    'server.threads.hintCpu':
        '推理使用的 CPU 线程数，建议不超过物理核心数（如 10 核设 6–8）',
    'server.threads.hintGpu':
        '推理主要在显卡，线程数建议 4–8，留出 CPU 给系统与音频',
    'server.start': '启动',
    'server.stop': '停止',
    'server.scanFailed': '扫描失败: {error}',
    'server.exeNotFound': '未找到 audiocpp_server.exe',
    'server.exeNotFoundHint':
        '请将版本目录放入 {dir}，或在设置页修改路径。',
    'server.rescan': '重新扫描',
    'server.openDir': '打开目录',
    'server.getServer': '获取服务端',
    'server.needModel': '请先在模型库安装一个模型，服务端才能启动。',
    'server.startNoVersion': '未找到可用的 audio.cpp 服务端版本，请检查版本目录或重新扫描。',
    'server.versionDir': '版本目录',
    'server.status.running': '运行中',
    'server.status.starting': '启动中',
    'server.status.stopping': '停止中',
    'server.status.error': '错误',
    'server.status.stopped': '已停止',
    'server.lockHint': '服务端运行中，请先停止当前服务端再修改该参数',
    'server.version': '版本: {name}',
    'server.backendInfo': '后端: {backend} · 已注册模型: {count}',
    'server.logTitle': '服务端日志',
    'server.logClear': '清空',
    'server.logEmpty': '暂无日志',
    'voices.title': '音色库',
    'voices.add': '添加',
    'voices.empty': '暂无音色',
    'voices.emptyHint': '点击右上角"添加"创建音色。',
    'voices.deleteTooltip': '删除',
    'voices.editTooltip': '编辑',
    'voices.deleteTitle': '删除音色',
    'voices.deleteConfirm': '确定删除"{name}"？',
    'voices.addTitle': '添加音色',
    'voices.editLabel': '编辑',
    'voices.name': '名称 *',
    'voices.nameHelper': '必填，作为参考音色的标识',
    'voices.noFile': '未选择参考音频',
    'voices.pickFile': '选择文件',
    'voices.textLabel': '参考文本（可选）',
    'voices.textHelper': '音频对照文本，便于音色克隆时参考',
    'voices.descLabel': '描述（可选）',
    'voices.langLabel': '语言（可选）',
    'voices.langHelper': '如 zh / en / ja',
    'voices.audioTypes': 'WAV / MP3 / FLAC / M4A / AAC 音频',
    'models.setAsCurrent': '设为当前',
    'models.startDownload': '开始下载',
    'models.tab.catalog': '模型库',
    'models.tab.downloads': '下载',
    'models.searchHint': '搜索模型名 / 包名 / 家族...',
    'models.refresh': '刷新（重新读取本地权重目录）',
    'models.empty': '暂未加载模型',
    'models.emptyFiltered': '没有匹配"{query}"的模型',
    'models.noSpecs.title': '当前 audio.cpp 版本未提供模型规格',
    'models.noSpecs.hint':
        '选中版本目录下缺少 model_specs/（{path}）。请切换到包含 model_specs 的版本。',
    'models.noServer.title': '未找到 audio.cpp 服务端',
    'models.noServer.hint':
        '在配置的目录下未找到 audiocpp_server.exe，请先到“服务”页设置版本目录并选择版本。',
    'models.noServer.action': '前往服务页',
    'models.section.installed': '已安装 ({count})',
    'models.section.notInstalled': '未安装 ({count})',
    'models.download.empty': '暂无下载任务',
    'models.download.processing': '下载中 ({count})',
    'models.download.finished': '最近完成 ({count})',
    'models.badge.recommended': '推荐',
    'models.badge.installed': '已安装',
    'models.badge.current': '当前',
    'models.downloading': '下载中',
    'models.download.title': '下载{name}',
    'models.download.chooseSpec': '选择要下载的规格包：',
    'models.download.tokenLabel': '访问口令（可选）',
    'models.download.tokenHint': '私有/受限模型需填写访问口令',
    'models.download.viewLicense': '查看许可 / 来源',
    'models.download.sourceRepo': '数据来自',
    'models.download.gated':
        '受限仓库：需先在来源站点接受其条款，并提供访问口令（token）后才能下载。',
    'models.sourceLabel': '下载源',
    'models.memory': '内存 ~{size}',
    'models.vram': '内存/显存 ~{size}',
    'models.revision.local': '本地 {rev}',
    'models.revision.remote': '远端 {rev}',
    'models.specCount': '{count} 个规格包',
    'models.uninstall.title': '卸载模型',
    'models.uninstall.confirm': '确定卸载 {id}？将删除已下载的权重文件。',
    'models.manage.title': '管理 {name}',
    'models.manage.hintSingle':
        '共 {total} 个规格包，当前仅安装 {installed} 个。先点击下方其他规格包的“下载”安装，安装后该行会出现“设为当前”按钮即可切换。',
    'models.manage.hintMulti':
        '共 {total} 个规格包，已安装 {installed} 个。在已安装的规格包行点击“设为当前”即可切换当前使用版本。',
    'models.experimental': '实验性',
    'models.task.done': '已完成',
    'models.task.installed': '已安装',
    'models.task.failed': '失败',
    'models.task.cancelled': '已取消',
    'models.task.paused': '已暂停',
    'models.task.downloading': '下载中',
    'models.task.redownload': '重新下载',
    'models.task.remove': '移除',
    'models.task.pause': '暂停',
    'models.task.resume': '继续',
    'models.task.cancel': '取消',
    'models.task.preparing': '准备中...',
    'models.task.eta': '剩余 {time}',
    'models.cat.tts': '语音合成',
    'models.cat.asr': '语音识别',
    'models.cat.clone': '克隆',
    'models.cat.vc': '变声/声音转换',
    'models.cat.separation': '音源分离',
    'models.cat.singing': '歌声合成',
    'models.cat.music': '音乐生成',
    'models.cat.audioGeneration': '音频生成',
    'models.cat.audioTools': '音频工具',
    'models.cat.speechAnalysis': '语音分析',
    'models.cat.community': '社区',
    'models.cat.general': '通用',
  };

  static const Map<String, String> en = <String, String>{
    'app.title': 'audio.cpp Desk',
    'nav.models': 'Models',
    'nav.downloads': 'Downloads',
    'nav.voices': 'Voices',
    'nav.server': 'Server',
    'nav.workbench': 'Workbench',
    'nav.settings': 'Settings',
    'nav.history': 'History',
    'history.title': 'History (work in progress)',
    'history.hint':
        'Generation history of TTS / cloning / separation tasks will be kept here.',
    'workbench.noModels':
        'No TTS / ASR models installed. Install one from the model library first.',
    'task.busy.title': 'Task in progress',
    'task.busy.message':
        'A task is generating. You can pause it first, or wait for it to finish before proceeding.',
    'task.busy.goWorkbench': 'Go to workbench',
    'workbench.model': 'Model',
    'workbench.textHint': 'Type the text to speak...',
    'workbench.voice': 'Voice',
    'workbench.defaultVoice': 'Default',
    'workbench.referenceText': 'Reference text',
    'workbench.referenceTextHint': 'Optional: transcript of the reference audio',
    'workbench.instruction': 'Instruction / style',
    'workbench.voiceId': 'Voice id',
    'workbench.customVoice': 'Custom…',
    'workbench.needInstruction': 'This model requires an instruction / style',
    'workbench.language': 'Language',
    'workbench.pickAudio': 'Choose audio',
    'workbench.submit': 'Add task',
    'workbench.advanced': 'Advanced',
    'workbench.advancedTitle': 'Advanced parameters',
    'workbench.reset': 'Reset',
    'workbench.default': 'Default',
    'workbench.defaultValue': 'Default ({value})',
    'workbench.invalidValue': 'Invalid value for "{name}"',
    'workbench.emotion': 'Emotion',
    'workbench.emotion.none': 'Default',
    'workbench.emotion.reference': 'Emotion reference audio',
    'workbench.emotion.vector': 'Emotion vector',
    'workbench.emotion.text': 'Emotion text',
    'workbench.emotion.strength': 'Emotion strength',
    'workbench.emotion.pickAudio': 'Choose emotion reference audio',
    'workbench.emotion.needAudio': 'Choose the emotion reference audio first',
    'workbench.result': 'Result',
    'workbench.needText': 'Please enter the text first',
    'workbench.needReference': 'This model needs a reference voice; choose one first',
    'workbench.needReferenceText': 'This model requires the reference text',
    'workbench.needAudio': 'Please choose an audio file first',
    'workbench.serverNotReady':
        'Server not ready. Configure the audio.cpp version on the Server page and start it first.',
    'workbench.memoryReleaseFailed':
        'Failed to release GPU memory; the generation queue has been stopped. Restart the server on the Server page, then continue.',
    'workbench.error': 'Submit failed',
    'workbench.modelMissing': 'Model not available (may be uninstalled)',
    'workbench.wavOnly':
        'Built-in transcoder not found; only WAV audio is supported',
    'workbench.transcodeFailed': 'Audio transcode failed',
    'workbench.saved': 'Saved to {path}',
    'workbench.generating': 'Generating · {time}',
    'workbench.elapsed': 'Elapsed {time}',
    'player.play': 'Play',
    'player.pause': 'Pause',
    'session.name': 'Session name',
    'session.unnamed': 'Unnamed session',
    'session.new': 'New session',
    'session.records': 'Session records',
    'session.tasks': 'Tasks',
    'task.queued': 'Queued',
    'task.pause': 'Pause',
    'task.resume': 'Start',
    'task.clear': 'Clear',
    'session.empty': 'No records yet',
    'session.open': 'Open',
    'session.delete': 'Delete session',
    'session.deleteConfirm': 'Delete this session and its audio?',
    'session.record.delete': 'Delete record',
    'session.export': 'Export',
    'session.saved': 'Saved',
    'history.empty': 'No sessions yet',
    'history.records': '{count} records',
    'history.clear': 'Clear history',
    'history.clearConfirm': 'Delete all sessions and audio?',
    'history.opened': 'Session loaded',
    'collection.none': 'Unfiled',
    'collection.unnamed': 'Collection',
    'collection.label': 'Collection',
    'collection.new': 'New collection',
    'collection.delete': 'Delete collection',
    'collection.deleteConfirm': 'Remove this collection? Its sessions are kept as unfiled.',
    'collection.move': 'Move to collection',
    'collection.up': 'Up',
    'collection.down': 'Down',
    'record.status.generating': 'Generating',
    'record.status.done': 'Done',
    'record.status.failed': 'Failed',
    'record.noOutput': 'No output',
    'record.type.tts': 'TTS',
    'record.type.asr': 'ASR',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.copied': 'Copied',
    'common.copyFailed': 'Copy failed',
    'common.download': 'Download',
    'common.manage': 'Manage',
    'common.uninstall': 'Uninstall',
    'common.delete': 'Delete',
    'settings.title': 'Settings',
    'settings.directories': 'Directories',
    'settings.dataRestart': 'Data directory changed. Please restart the app.',
    'settings.language': 'Language',
    'settings.showExperimental': 'Show experimental entries',
    'settings.showExperimental.subtitle':
        'Show experimental / community entries in the model library',
    'settings.serverLog': 'Persist server logs',
    'settings.serverLog.subtitle':
        'Server run logs are saved to {dir} for troubleshooting',
    'settings.appLog': 'App logs',
    'settings.appLog.subtitle':
        "Record this app's own activity (directories, model library, tasks, errors) to {dir} for troubleshooting",
    'settings.taskTimeout': 'Task timeout',
    'settings.taskTimeout.subtitle':
        'A task not finished within this duration is marked failed.',
    'settings.audioCppDesc':
        'audio.cpp version directory (can contain multiple versions)',
    'settings.audioCppHint': 'audio.cpp or absolute path',
    'settings.modelsLabel': 'Model directory',
    'settings.modelsHint': 'models or absolute path',
    'settings.dataLabel': 'Data directory (backup = copy this directory)',
    'settings.dataHint': 'data or absolute path',
    'settings.saved':
        'Directories saved (audio.cpp / models / data); the server page will rescan automatically.',
    'settings.pickDir': 'Choose directory',
    'settings.about': 'About',
    'settings.about.desc':
        'A desktop client for audio.cpp. audio.cpp itself is not provided with this software; obtain it separately.',
    'settings.about.source':
        'Model specs and descriptions are derived from the official audio.cpp repository and documentation (Apache-2.0, © ShugoAI LLC).',
    'settings.about.license': 'Open-source licenses',
    'settings.about.homepage': 'Project',
    'settings.about.upstream': 'Upstream',
    'models.currentVersion': 'Current version',
    'server.title': 'Server Control',
    'server.status.label': 'Server',
    'server.status.start': 'Start',
    'server.status.stop': 'Stop',
    'server.status.models': 'Registered models {count}',
    'server.status.backend': 'Backend',
    'server.backend': 'Backend',
    'server.readingBackends': 'Reading backend capabilities…',
    'server.device': 'Device',
    'server.device.cpu': 'CPU',
    'server.device.gpuItem': 'GPU {index} · {name}',
    'server.threads': 'Threads',
    'server.threads.hintCpu':
        'CPU threads for inference; keep it at or below your physical core count (e.g. 6-8 on a 10-core CPU)',
    'server.threads.hintGpu':
        'Inference runs mainly on the GPU; 4-8 is enough, leaving CPU for the system and audio',
    'server.start': 'Start',
    'server.stop': 'Stop',
    'server.scanFailed': 'Scan failed: {error}',
    'server.exeNotFound': 'audiocpp_server.exe not found',
    'server.exeNotFoundHint':
        'Put the version directory in {dir}, or change the path in settings.',
    'server.rescan': 'Rescan',
    'server.openDir': 'Open directory',
    'server.getServer': 'Get server',
    'server.needModel': 'Install a model from the model library before starting the server.',
    'server.startNoVersion': 'No audio.cpp server version found. Check the version directory or rescan.',
    'server.versionDir': 'Version directory',
    'server.status.running': 'Running',
    'server.status.starting': 'Starting',
    'server.status.stopping': 'Stopping',
    'server.status.error': 'Error',
    'server.status.stopped': 'Stopped',
    'server.lockHint': 'The server is running. Stop it first to change this.',
    'server.version': 'Version: {name}',
    'server.backendInfo': 'Backend: {backend} · Registered models: {count}',
    'server.logTitle': 'Server log',
    'server.logClear': 'Clear',
    'server.logEmpty': 'No logs',
    'voices.title': 'Voice Library',
    'voices.add': 'Add',
    'voices.empty': 'No voices',
    'voices.emptyHint':
        'Click "Add" at the top right to create a voice.',
    'voices.deleteTooltip': 'Delete',
    'voices.editTooltip': 'Edit',
    'voices.deleteTitle': 'Delete voice',
    'voices.deleteConfirm': 'Delete "{name}"?',
    'voices.addTitle': 'Add voice',
    'voices.editLabel': 'Edit',
    'voices.name': 'Name *',
    'voices.nameHelper': 'Required, used as an identifier for the reference voice',
    'voices.noFile': 'No reference audio selected',
    'voices.pickFile': 'Choose file',
    'voices.textLabel': 'Reference text (optional)',
    'voices.textHelper': 'Audio transcript, useful as a reference for voice cloning',
    'voices.descLabel': 'Description (optional)',
    'voices.langLabel': 'Language (optional)',
    'voices.langHelper': 'e.g. zh / en / ja',
    'voices.audioTypes': 'Audio (WAV / MP3 / FLAC / M4A / AAC)',
    'models.setAsCurrent': 'Set as current',
    'models.startDownload': 'Start download',
    'models.tab.catalog': 'Model Library',
    'models.tab.downloads': 'Downloads',
    'models.searchHint': 'Search model name / package / family...',
    'models.refresh': 'Refresh (rescan local weights directory)',
    'models.empty': 'No models loaded',
    'models.emptyFiltered': 'No models match "{query}"',
    'models.noSpecs.title': 'The current audio.cpp version provides no model specs',
    'models.noSpecs.hint':
        'The selected version directory has no model_specs/ ({path}). Switch to a version that ships model_specs.',
    'models.noServer.title': 'audio.cpp server not found',
    'models.noServer.hint':
        'No audiocpp_server.exe was found under the configured directory. Set the versions directory and pick a version on the Server page first.',
    'models.noServer.action': 'Go to Server',
    'models.section.installed': 'Installed ({count})',
    'models.section.notInstalled': 'Not installed ({count})',
    'models.download.empty': 'No download tasks',
    'models.download.processing': 'Downloading ({count})',
    'models.download.finished': 'Recently finished ({count})',
    'models.badge.recommended': 'Recommended',
    'models.badge.installed': 'Installed',
    'models.badge.current': 'Current',
    'models.downloading': 'Downloading',
    'models.download.title': 'Download {name}',
    'models.download.chooseSpec': 'Choose a spec package to download:',
    'models.download.tokenLabel': 'Access token (optional)',
    'models.download.tokenHint': 'Required for private / restricted models',
    'models.download.viewLicense': 'View license / source',
    'models.download.sourceRepo': 'Data source',
    'models.download.gated':
        'Gated repository: accept its terms on the source site and provide an access token to download.',
    'models.sourceLabel': 'Source',
    'models.memory': 'Memory ~{size}',
    'models.vram': 'RAM/VRAM ~{size}',
    'models.revision.local': 'Local {rev}',
    'models.revision.remote': 'Remote {rev}',
    'models.specCount': '{count} spec packages',
    'models.uninstall.title': 'Uninstall model',
    'models.uninstall.confirm':
        'Uninstall {id}? Downloaded weights will be deleted.',
    'models.manage.title': 'Manage {name}',
    'models.manage.hintSingle':
        '{total} spec packages in total, only {installed} installed. Click "Download" on another spec package below to install it; once installed, a "Set as current" button appears on that row.',
    'models.manage.hintMulti':
        '{total} spec packages in total, {installed} installed. Click "Set as current" on an installed row to switch the active version.',
    'models.experimental': 'Experimental',
    'models.task.done': 'Done',
    'models.task.installed': 'Installed',
    'models.task.failed': 'Failed',
    'models.task.cancelled': 'Cancelled',
    'models.task.paused': 'Paused',
    'models.task.downloading': 'Downloading',
    'models.task.redownload': 'Redownload',
    'models.task.remove': 'Remove',
    'models.task.pause': 'Pause',
    'models.task.resume': 'Resume',
    'models.task.cancel': 'Cancel',
    'models.task.preparing': 'Preparing...',
    'models.task.eta': 'ETA {time}',
    'models.cat.tts': 'Text-to-Speech',
    'models.cat.asr': 'Speech Recognition',
    'models.cat.clone': 'Cloning',
    'models.cat.vc': 'Voice Conversion',
    'models.cat.separation': 'Source Separation',
    'models.cat.singing': 'Singing Synthesis',
    'models.cat.music': 'Music Generation',
    'models.cat.audioGeneration': 'Audio Generation',
    'models.cat.audioTools': 'Audio Tools',
    'models.cat.speechAnalysis': 'Speech Analysis',
    'models.cat.community': 'Community',
    'models.cat.general': 'General',
  };

  /// 中文词典：zh 优先，缺词条时回退英文，保证任何语言下取词均可读。
  static final Map<String, String> _zhWithEnFallback = <String, String>{
    ...en,
    ...zh,
  };

  static Map<String, String> of(AppLocale locale) =>
      locale == AppLocale.zh ? _zhWithEnFallback : en;

  static String t(AppLocale locale, String key) =>
      of(locale)[key] ?? key;
}